# Generated by Django 4.0.10 on 2026-02-17 00:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0001_initial'),
        ('module', '0002_module_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum_module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('coefficient', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_modules', to='formation.formation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_modules', to='module.module')),
            ],
            options={
                'verbose_name': 'Curriculum_Module',
                'verbose_name_plural': 'Curriculum_Modules',
                'db_table': 'curriculum_module',
                'ordering': ['formation'],
            },
        ),
    ]
