# Generated by Django 4.0.10 on 2026-02-22 00:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum_module',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
