# Generated by Django 4.0.10 on 2026-02-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_alter_module_code'),
        ('formation', '0002_formation_updated_at_alter_formation_unique_together'),
        ('curriculum_module', '0002_alter_curriculum_module_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum_module',
            options={'ordering': ['formation', 'module', 'coefficient', 'created_at', 'semester', 'year', 'NE'], 'verbose_name': 'curriculum module', 'verbose_name_plural': 'curriculum modules'},
        ),
        migrations.AddField(
            model_name='curriculum_module',
            name='NE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum_module',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2')], null=True),
        ),
        migrations.AddField(
            model_name='curriculum_module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curriculum_module',
            name='year',
            field=models.CharField(blank=True, choices=[('1CP', '1st Year Preparatory'), ('2CP', '2nd Year Preparatory'), ('1CS', '1st Year Higher cycle'), ('2CS', '2nd Year Higher cycle'), ('3CS', '3rd Year Higher cycle'), ('L1', '1st Year License'), ('L2', '2nd Year License'), ('L3', '3rd Year License'), ('M1', '1st Year Master'), ('M2', '2nd Year Master'), ('D', 'Doctorate')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum_module',
            unique_together={('module', 'formation', 'semester', 'year')},
        ),
    ]
