# Generated by Django 4.0.10 on 2026-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_module', '0003_alter_curriculum_module_options_curriculum_module_ne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum_module',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
