# Generated by Django 4.0.10 on 2026-02-22 00:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_alter_curriculum_options_alter_curriculum_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum_module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Periode',
                'verbose_name_plural': 'Periodes',
                'db_table': 'periode',
                'ordering': ['curriculum', 'rank'],
            },
        ),
    ]
