# Generated by Django 4.0.10 on 2026-02-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_curriculum_options_alter_curriculum_id_and_more'),
        ('periode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curriculum_module',
            new_name='Periode',
        ),
    ]
