# Generated by Django 4.0.10 on 2026-02-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_curriculum_moyenne_rattrapage_and_more'),
        ('periode', '0002_rename_curriculum_module_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='curriculum.curriculum'),
        ),
    ]
