# Generated by Django 4.0.10 on 2026-02-23 01:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0003_alter_module_code'),
        ('periode', '0003_periode_updated_at_alter_periode_credits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(blank=True, choices=[('NORMAL', 'GRADE NORMAL'), ('RATTR', 'GRADE RATTRAPAGE'), ('RACHA', 'GRADE RACHAT'), ('CONCOURS', 'GRADE CONCOURS')], max_length=20, null=True)),
                ('source', models.CharField(blank=True, choices=[('OCR', 'OCR'), ('MANUAL', 'MANUAL'), ('IMPORT', 'IMPORT')], max_length=20, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('ects', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='module.module')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='periode.periode')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'grade',
                'ordering': ['period__name', 'module__name', 'status', 'note'],
                'unique_together': {('period', 'module')},
            },
        ),
    ]
