# Generated by Django 4.0.10 on 2026-03-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum_module', '0003_alter_curriculum_module_options_curriculum_module_ne_and_more'),
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['period__name', 'module__module__name', 'status', 'note'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='curriculum_module.curriculum_module'),
        ),
    ]
