# Generated by Django 4.0.10 on 2026-02-16 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_program_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='speciality',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
