# Generated by Django 4.0.10 on 2026-02-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_module_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
