# Generated by Django 4.0.10 on 2026-02-16 01:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '0002_program_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation', to='program.program')),
            ],
            options={
                'verbose_name': 'formation',
                'verbose_name_plural': 'formations',
                'db_table': 'formation',
                'ordering': ['year'],
            },
        ),
    ]
