# Generated by Django 4.0.10 on 2026-02-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_program_updated_at_alter_program_code_and_more'),
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='formation',
            unique_together={('name', 'year', 'program')},
        ),
    ]
