# Generated by Django 4.0.10 on 2026-02-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_program_updated_at_alter_program_code_and_more'),
        ('formation', '0002_formation_updated_at_alter_formation_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['created_at'], 'verbose_name': 'formation', 'verbose_name_plural': 'formations'},
        ),
        migrations.AlterUniqueTogether(
            name='formation',
            unique_together={('name', 'program')},
        ),
        migrations.RemoveField(
            model_name='formation',
            name='year',
        ),
    ]
