# Generated by Django 4.0.10 on 2026-02-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['matricule'], 'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiant'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
