# Generated by Django 4.0.10 on 2026-02-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['matricule'], 'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
    ]
