# Generated by Django 4.0.10 on 2026-02-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
