# Generated by Django 4.0.10 on 2026-02-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Null', 'Null')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
