# Generated by Django 4.0.10 on 2026-02-21 21:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0005_alter_student_birth_date'),
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('moyenne_rachat', models.FloatField(blank=True, null=True)),
                ('moyenne_finale', models.FloatField(blank=True, null=True)),
                ('moyenne_concours', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='formation.formation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='student.student')),
            ],
        ),
    ]
