# Generated by Django 4.0.10 on 2026-02-22 00:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
        ('student', '0005_alter_student_birth_date'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['formation', 'rank'], 'verbose_name': 'Curriculum', 'verbose_name_plural': 'Curriculums'},
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together={('student', 'formation')},
        ),
        migrations.AlterModelTable(
            name='curriculum',
            table='curriculum',
        ),
    ]
