# Generated by Django 4.0.10 on 2026-02-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_curriculum_options_alter_curriculum_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='moyenne_rattrapage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='status',
            field=models.CharField(blank=True, choices=[('ADMIS', 'Admis'), ('INSCRIT', 'Inscrit'), ('EXCLU', 'Exclu'), ('RACHAT', 'Admis avec rachat'), ('RATTRAPAGE', 'Admis en rattrapage')], max_length=20, null=True),
        ),
    ]
